### ISSUE TITLE
Can't seem to get the generic API to work

### ISSUE THREAD

**Issue by robboz4** [washcroft/homebridge-http-garagedoorcontroller#10]
I'm trying to use the generic  API config setting and I get the following error:
[2/12/2018, 3:17:52 PM] [Toy Pod] ERROR in _checkStates() - ERROR in _determineDoorState() - An error occurred during the HTTP request: getaddrinfo ENOTFOUND 192.168.1.13test 192.168.1.13test:80

My api config is: 
{
            "accessory": "HttpGarageDoorController",
            "name": "Toy Pod",
      
            "httpHost": "192.168.1.13",
            "httpPort": 80,
            "httpSsl": false,
            "httpStatusPollMilliseconds": 60000,
            "httpRequestTimeoutMilliseconds": 10000,      
            "apiConfig":
            {
              "apiType": "Generic",
           
              "doorOpenMethod": "GET",
              "doorOpenUrl": "test/open",
              "doorOpenSuccessContent": "OK",
        
              "doorCloseMethod": "GET",
              "doorCloseUrl": "test/close",
              "doorCloseSuccessContent": "OK",
        
             "doorStateMethod": "GET",
             "doorStateUrl":"test/status" 
            }
       },

 The files are there and should return "OK". I tried putting a "/" in front  of the  "test/" in the Url fields but that generates a 404 error.

I'm trying to simply pass this to the server 192.168.1.13

HB_Link?num=x&op=OPEN|CLOSE|STATUS

where x = 1, 2 or 3 and one of the op parameters. The PHP code works when called from a browser window. As that didn't work I tried  to hit the  files as per your example, but I get the above error. That error also is returned when I substitute my full Url requests.

The above entry is for one of my 3 doors. The doors show up accurately in the homebridge display.  The config.json file passes the lint test and my other devices are still working. Do you have any suggestions why I can't pass 192.168.1.13/test/HB_Link&num=1&op=STATUS from the generic API?

**Comment by robboz4** [comment]
I've been looking at this some more and discovered that you ca not use any further directory links. I moved my file up to the web root. Next step was to remove the .php. Now I  have the response working I just have to work out how to get the internals working to connect to my garage code. Here's a snippet of my current working config.json.
{
            "accessory": "HttpGarageDoorController",
            "name": "Dave's Pod",
      
            "httpHost": "homebridge.local",
            "httpPort": 80,
            "httpSsl": false,
            "httpStatusPollMilliseconds": 60000,
            "httpRequestTimeoutMilliseconds": 10000,      
            "apiConfig":
            {
              "apiType": "Generic",
           
              "doorOpenMethod": "GET",
              "doorOpenUrl": "/hblink?num=1&op=open",
              "doorOpenSuccessContent": "OK",
        
              "doorCloseMethod": "GET",
              "doorCloseUrl": "/close",
              "doorCloseSuccessContent": "OK",
        
             "doorStateMethod": "GET",
             "doorStateUrl":"/status" 
            }
       }

**Comment by robboz4** [comment]
Looks like generic Api won't work for me as you can't pass any parameters into the web server. Not sure if this a node issue or the plugin not passing full URL data through. So far I can read the value of status, but as I can't take any actions on open and close. pretty much stuck.  It does look good in the homelink app though.


Cheers

Dave

**Comment by robboz4** [comment]
Reopened as I closed by accident. Is it an issue with api or node?

**Comment by washcroft** [comment]
> The files are there and should return "OK". I tried putting a "/" in front of the "test/" in the Url fields but that generates a 404 error.

You do need the leading "/", then the 404 is coming from the web server.

> I've been looking at this some more and discovered that you ca not use any further directory links. I moved my file up to the web root.

> Looks like generic Api won't work for me as you can't pass any parameters into the web server.

Shouldn't be necessary, whatever URL you configure (path and query string), will be what is requested from the web server.

Does your web server produce any logs or output to show what URL is actually being requested?

**Comment by robboz4** [comment]
I added back in all the authorization and HTTp header information. That seemed to fix it.. I can now send the parameters and get status back. I still have some work to do on my side for the final integration. 
In summary, there is a bug with the code as it needs ALL the http header and authorization variables to be included. Nothing is optional as far as I can tell.

Thanks for the assistance!  Siri is now opening and closing my "garage doors". Well at least my test code.

**Comment by OhHeyAlan** [comment]
Robboz4, can you branch your working code?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by robboz4** [comment]
There’s no change to any code, only the values in the config.json file. My test code receives the requests. The status request gets a response back on the state of the door. The test code is a simple php file that uses echo to return the state. I still have to interface it to my-garage code
(https://github.com/robboz4/My-Garage). Do you want me to post the test code or my working config.json file?

**Comment by OhHeyAlan** [comment]
@robboz4 Your working config.json file

**Comment by robboz4** [comment]
Here it is:


[config.json.zip](https://github.com/washcroft/homebridge-http-garagedoorcontroller/files/1734113/config.json.zip)
