### ISSUE TITLE
Multiple Garage Doors

### ISSUE THREAD

**Issue by robboz4** [washcroft/homebridge-http-garagedoorcontroller#3]
Hi! 
I'm new to Homebridge, npm etc.,  and saw your plugin and would like to leverage it for my internet connected garage door opener (https://github.com/robboz4/My-Garage). I have three doors and no switchable lights. Right now I don't return a status via http so I know I need to implement that. I was curious as to how I would configure three doors? I tried a quick hack of the config.json file, but always gives me the last entry in the garage table. So I'm assuming I would need to identify the three doors in the index.json file.
My rudimentary test of replacing the URL and the command in the config.json file produce  an icon in the homekit screen, but due to the lack of status there wasn't much else.

Thanks for creating this plugin and hopefully I can leverage it into my three door system.

**Comment by washcroft** [comment]
Hello,
Thanks for your email, sorry for the delayed response.

You should be able to have multiple instances of the same module/accessory simply by creating three whole blocks of config in the HomeBridge config.json file.

Best Regards,
Warren Ashcroft

**Comment by robboz4** [comment]
Thanks for the reply. I’ll look into that. I had to remove my earlier entry to config.json as it started to cause problems with the whole AppleTv, iPad connection. I have a new install now all up and running on the latest iOS and TV os, so will how it goes. I’ll remove the light  entry as I can’t switch on the light separately from my door operation. Will keep you posted.
