### ISSUE TITLE
Idea: Adding behaviour to stop closing door

### ISSUE THREAD

**Issue by gopi-ar** [washcroft/homebridge-http-garagedoorcontroller#5]
I use your wonderful plugin to work with my house's sliding gate. There's some benefit to having it stop mid-way - 2 wheelers coming in, people walk in, etc. Our gate motor (NICE), needs the same switch pressed twice to halt. For e.g., If the gate was opening, I'd have to press open again to stop the gate; if I press close, it'll close the gate instead.

I understand you don't need it for a garage door, but any ideas on how that could be implemented?

**Comment by washcroft** [comment]
If the door/gate is opening or closing, tapping the door again in the Home app would send the opposite command to the API, so this would depend on what's on the other end of the API to do what you need (i.e. if the close command received, whilst opening, simply stop).

Alternatively, exposing some other "hold" switch/button in HomeKit that you could press to stop the movement might be an option.

**Comment by gopi-ar** [comment]
That's interesting, thanks!
