### ISSUE TITLE
lightstate is ignored when using split door and light status service

### ISSUE THREAD

**Issue by estenwig** [washcroft/homebridge-http-garagedoorcontroller#6]
Hi, thanks for a nice plugin!

I found that when I tried to use a separate endpoint for retrieving the status for the light and another one for the door the status for the light was overwritten.
When I created a combined status URL that returned both door-status and lightstatus it seems to work.

**Comment by washcroft** [comment]
I can't see how this is possible in the code, especially when the door state url and light state url are configured differently.

What does / did your config look like when it was behaving like this?
