### ISSUE TITLE
httpssl invalid protocol

### ISSUE THREAD

**Issue by horsehay** [washcroft/homebridge-http-garagedoorcontroller#7]
Is this a bug or missing library?

`ERROR in _checkStates() - ERROR in _determineDoorState() - An error occurred during the HTTP request: Invalid protocol: httpssl:`

**Comment by horsehay** [comment]
Found the issue on line 708.

**Comment by jeylites** [comment]
@horsehay I'm in the same issue as you. What was the fix?

**Comment by washcroft** [comment]
@jeylites The fix has already been committed to the master branch.
